### ISSUE TITLE
First Boss

### ISSUE THREAD

**Issue by PatrickSantoZZ** [Owyn/nest-guide#1]
Is it possible to upgrade the mod from last boss to both bosses ? :)

**Comment by Owyn** [comment]
Pretty much all attacks on 1st boss are well distinguishable, so not so sure about it 🤔

**Comment by PatrickSantoZZ** [comment]
Its just a idea for guys who dont wanna learn the mechs :D

**Comment by Owyn** [comment]
I mean... there's nothing to learn there 👀  just evade when Boss starts to look menacing

**Comment by AntiScrewdriver** [comment]
i'm in NA ... which dungeon is Parquina's Nest ? Latest dungeon we got was Gossamer's Vault, is that the one ?

**Comment by Owyn** [comment]
One with Insects in it

**Comment by PatrickSantoZZ** [comment]
Gossamer's Vault = Parquina's Nest. its the same Dungeon with different names xd
