### ISSUE TITLE
Hard Mode when ? xD

### ISSUE THREAD

**Issue by Coldsorc** [Owyn/nest-guide#2]

**Comment by Owyn** [comment]
when RU-tera gets it obviously 🤷‍♀

**Comment by Peckspas** [comment]
When does RU get it? This guide is so well made im waiting for the hard mode version aswell for EU

**Comment by Owyn** [comment]
Date not yet announced by RU publisher

**Comment by Owyn** [comment]
You could try using https://github.com/Owyn/Boss-Skill-Logger which would show in chat skill IDs of boss attacks which I could add into the guide right after you send those to me (along with what they mean (what text to make for them in notice)) if you want to get the HM guide ready sooner

**Comment by Peckspas** [comment]
I hope someone reads this and does it. Would be sad if we had to wait weeks for this guide. I cant run GVH yet sadly (lvl 68 requirement lol)

**Comment by kriiszmae** [comment]
ok i will try
what exactly u will need?
my proxy chat? or there will be a file in the mod folder that i need to pass u?
also, do i need to finish the dung? coz we are wiping a lot

**Comment by Owyn** [comment]
Updated link above to point to my fork (since original was no longer working)

> what exactly u will need?

it will write skill ids and at which %hp boss did it in the proxy chat when boss does something
the skills you would like to be announced in notice chat - send their skill ids to me here and say what those are exactly (how to name them in notice"), example: 
```
108: {msg: 'Back attack!'},
235: {msg: 'Debuffs'},
230: {msg: 'AOE'},
228: {msg: 'Team up'}
```

**Comment by Owyn** [comment]
Some nice man sent me a new dungeon zone id, and now guide works in HM too cuz of it, enjoy 😃
