### ISSUE TITLE
First Boss

### ISSUE THREAD

**Issue by Peckspas** [Owyn/nest-guide#3]
Just wanted to report that there are still many attacks/mechs not displayed on this. Maybe someone can send them in?
I think right now attacks are only displayed during the "fast" phase of the boss. The same attacks during the "slow" phase never show up

**Comment by Owyn** [comment]
Indeed, added those just now, should work.  https://github.com/Owyn/nest-guide/commit/2d6ad638a4485db50fa713a8af12a465bd340a85
