### ISSUE TITLE
In/Out on 2nd boss showing as blank

### ISSUE THREAD

**Issue by MeowyMeow** [Owyn/nest-guide#6]
The announcement for in safe or out safe on gvn is not working. It simply sends a blank announcement. Everything else seems to be working. idk about gvh.

**Comment by Owyn** [comment]
🤔  it was working fine before thought, right? and nothing was changed...

**Comment by Zakhaev31** [comment]
GVH its the same its not working the IN / OUT

**Comment by Owyn** [comment]
Updated module, try latest version

If it doesn't help - try https://github.com/Owyn/Boss-Skill-Logger
and see what it writes about those In \ OUT boss skills

**Comment by Zakhaev31** [comment]
> Updated module, try latest version
> 
> If it doesn't help - try https://github.com/Owyn/Boss-Skill-Logger
> and see what it writes about those In \ OUT boss skills

i tested the new fix on GVN and its fixed, dunno yet in GVH, but probably is fixed
